spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tasklytodoapp}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: WARN
    com.tasklytodoapp: INFO